#!/bin/bash
#
# (c) 2024 - BlueRockTEL. <hello@bluerocktel.com>
#
# This file is part of Pbx3cxFetchAndStoreBackups.
#
# Pbx3cxFetchAndStoreBackups is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pbx3cxFetchAndStoreBackups is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pbx3cxFetchAndStoreBackups. If not, see <http://www.gnu.org/licenses/>

source .env
working_directory=$(pwd)

input="${working_directory}/hosts"

while IFS= read -r host
do
    for i in {6..2}
    do
        day=$(date -d "$i days ago" +a)
        echo "clean up host ${host} for day ${day}"
        rm -rf "${worker_backups_path}/${host}/${day}"
    done
done < "$input"
