#!/bin/bash
#
# (c) 2024 - BlueRockTEL. <hello@bluerocktel.com>
#
# This file is part of Pbx3cxFetchAndStoreBackups.
#
# Pbx3cxFetchAndStoreBackups is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pbx3cxFetchAndStoreBackups is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pbx3cxFetchAndStoreBackups. If not, see <http://www.gnu.org/licenses/>

source .env

files=(
    .env
    check_backups
    hosts
    fetch_backups
    fetch_backups_parallel
    notify
    store_backups
    store_backups_parallel
)

for file in "${files[@]}"; do
    scp -P ${worker_port} $file ${worker_user}@${worker}:${worker_path}/
done
