#!/bin/bash
#
# (c) 2024 - BlueRockTEL. <hello@bluerocktel.com>
#
# This file is part of Pbx3cxFetchAndStoreBackups.
#
# Pbx3cxFetchAndStoreBackups is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pbx3cxFetchAndStoreBackups is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pbx3cxFetchAndStoreBackups. If not, see <http://www.gnu.org/licenses/>

source .env

mkdir -p "${worker_path}/logs"
connections_ok_file="${worker_path}/logs/connections_ok.txt"
connections_ko_file="${worker_path}/logs/connections_ko.txt"
rm "$connections_ok_file"
rm "$connections_ko_file"
touch "$connections_ok_file"
touch "$connections_ko_file"

journal="${worker_path}/logs/fetch_journal.txt"
rm "$journal"
touch "$journal"

current_date=$(date +"%Y%m%d")
current_journal="${worker_path}/logs/fetch_journal_$current_date.txt"
touch "$current_journal"

split -l 10 -d hosts "hosts_fetch_batch_"

file_array=()

while IFS=  read -r -d $'\0'; do
    file_array+=("$REPLY")
done < <(find . -type f -name 'hosts_fetch_batch_*' -print0)

for file in "${file_array[@]}"; do
    ./fetch_backups $file &
done

wait

rm hosts_fetch_batch_*
