#!/bin/bash
#
# (c) 2024 - BlueRockTEL. <hello@bluerockel.com>
#
# This file is part of Pbx3cxFetchAndStoreBackups.
#
# Pbx3cxFetchAndStoreBackups is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pbx3cxFetchAndStoreBackups is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pbx3cxFetchAndStoreBackups. If not, see <http://www.gnu.org/licenses/>

source .env
working_directory=$(pwd)

subject="3cx Backups Check"
backups_ok_file="${working_directory}/logs/backups_ok.txt"
backups_ko_file="${working_directory}/logs/backups_ko.txt"
fetch_journal="${working_directory}/logs/fetch_journal.txt"
store_journal="${working_directory}/logs/store_journal.txt"

backups_ok_count=$(wc -l < "$backups_ok_file")
backups_ko_count=$(wc -l < "$backups_ko_file")

((backups_ok_count--))
((backups_ko_count--))

body="Hello there,

3cx backups agent here.

Number of Backups OK: $backups_ok_count
Number of Backups KO: $backups_ko_count

Please check the attached files for details.

Have a nice day Guys.

Pbx3cxFetchAndStoreBackups
https://bluerocktel.com
"

echo "$body" | mailx -s "$subject" -a "$backups_ok_file" -a "$backups_ko_file" -a "$fetch_journal" -a "$store_journal" "$notified"
