#!/bin/bash

mkdir -p "${working_directory}/logs"

journal="${working_directory}/logs/store_journal.txt"
rm "$journal"
touch "$journal"

current_date=$(date +"%Y%m%d")
current_journal="${working_directory}/logs/store_journal_$current_date.txt"
touch "$current_journal"

split -l 100 -d hosts "hosts_store_batch_"

file_array=()

while IFS=  read -r -d $'\0'; do
    file_array+=("$REPLY")
done < <(find . -type f -name 'hosts_store_batch_*' -print0)

for file in "${file_array[@]}"; do
    ./store_backups $file &
done

wait

rm hosts_store_batch_*
